version: '2'
services:
  db:
    image: postgres:10  
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: always             # run as a service  

  odoo11:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8090:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service  
